# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.IntegerField()),
                ('hpost_name', models.CharField(max_length=30)),
                ('district_name', models.CharField(max_length=20)),
                ('hfacility_type', models.CharField(max_length=30)),
            ],
        ),
    ]
