# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_care_invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpost',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
