# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_invoice_app', '0002_healthpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeMsgRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
