# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_invoice_app', '0003_welcomemsgrecipients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthpost',
            old_name='hfacility_type',
            new_name='hfacilitys_type',
        ),
    ]
