# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_invoice_app', '0011_auto_20190417_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='n_id',
            field=models.IntegerField(verbose_name=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
