# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_invoice_app', '0016_auto_20190417_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthpost',
            old_name='hfacility_type',
            new_name='health_facility_type',
        ),
        migrations.RenameField(
            model_name='healthpost',
            old_name='hpost_name',
            new_name='healthpost_name',
        ),
        migrations.RenameField(
            model_name='healthpost',
            old_name='n_id',
            new_name='national_id',
        ),
    ]
