# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_care_invoice_app', '0019_auto_20190417_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Of_Medical_Visit', models.CharField(max_length=15)),
                ('desease_Episode', models.CharField(max_length=15)),
                ('purpose_Of_The_Visit', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='dOB',
            field=models.CharField(default=6, max_length=4),
            preserve_default=False,
        ),
    ]
